### ISSUE TITLE
how do i add a list of nodes and draw edges between them ?

### ISSUE THREAD

**Issue by elia-orsini** [tohsaka888/knowledge-graph-demo#89]
I am trying to recreate a knowledge graph similar to the one in Obsidian but I don't understand how the code needs to be structured. Do you have a simple example with a few nodes and some edges connecting them like the one in the picture ? :)

thanks !

![image](https://github.com/tohsaka888/knowledge-graph-demo/assets/32492427/f0548e68-cf37-48fe-aa05-cba4b853e813)

**Comment by tohsaka888** [comment]
> I am trying to recreate a knowledge graph similar to the one in Obsidian but I don't understand how the code needs to be structured. Do you have a simple example with a few nodes and some edges connecting them like the one in the picture ? :)
> 
> thanks !
> 
> ![image](https://private-user-images.githubusercontent.com/32492427/270165698-f0548e68-cf37-48fe-aa05-cba4b853e813.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5OTIwNjksIm5iZiI6MTcwMzk5MTc2OSwicGF0aCI6Ii8zMjQ5MjQyNy8yNzAxNjU2OTgtZjA1NDhlNjgtY2YzNy00OGZlLWFhMDUtY2JhNGI4NTNlODEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDAzMDI0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiZTIwZTY5ZWY0YjFjNGMxMGE1MTMyMWFlNTZjMTBjYmI1Njc2ZWYwNjQ2MDM4NmQxYThiZTg0OGI1MjJmYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RSAkwgMZE8RCqcbXg92D3SgPCGtXARCtCmZezFHzJNQ)

Sorry I didn't get back to you until now.This repo is a demo of [react-knowledge-graph](https://github.com/tohsaka888/react-knowledge-graph).You can get the reference here.

**Comment by tohsaka888** [comment]
Here is the node's data structure.
```json
{
  "id": "node-0-01",
  "name": "test-01",
  "type": "test",
  "hasMore": true,
  "direction": "inside",
  "parentId": "node-0"
}
```
```json
{
  "_id": {
    "$oid": "633819a422b6c57df0fc38ff"
  },
  "id": "node-0-02",
  "name": "test-02",
  "type": "test",
  "hasMore": true,
  "direction": "inside",
  "parentId": "node-0"
}
```
and the edge data structure is like is:

```json
{
  "fromId": "node-0-01",
  "toId": "node-0-02",
  "description": "description",
  "id": "edge-1"
}
```
and the edge will connect from the node which the id is `node-0-01` to the node which the id is `node-0-02`.
